// default package
// Generated 18 nov. 2015 14:37:33 by Hibernate Tools 4.3.1.Final
//author : Alexandre Brosse

package ge_jpa.entities;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cheque generated by hbm2java
 */
@Entity
@Table(name = "cheque", catalog = "sql496886")
public class Cheque implements java.io.Serializable {

	private Integer chqId;
	private FraisInscription fraisInscription;
	private String chqNomBanque;
	private String chqNomEmetteur;
	private String chqPrenomEmetteur;
	private int chqNumCheque;
	private int chqMontant;
	private Date chqDateEncaissement;

	public Cheque() {
	}

	public Cheque(FraisInscription fraisInscription, String chqNomBanque, String chqNomEmetteur,
			String chqPrenomEmetteur, int chqNumCheque, int chqMontant) {
		this.fraisInscription = fraisInscription;
		this.chqNomBanque = chqNomBanque;
		this.chqNomEmetteur = chqNomEmetteur;
		this.chqPrenomEmetteur = chqPrenomEmetteur;
		this.chqNumCheque = chqNumCheque;
		this.chqMontant = chqMontant;
	}

	public Cheque(FraisInscription fraisInscription, String chqNomBanque, String chqNomEmetteur,
			String chqPrenomEmetteur, int chqNumCheque, int chqMontant, Date chqDateEncaissement) {
		this.fraisInscription = fraisInscription;
		this.chqNomBanque = chqNomBanque;
		this.chqNomEmetteur = chqNomEmetteur;
		this.chqPrenomEmetteur = chqPrenomEmetteur;
		this.chqNumCheque = chqNumCheque;
		this.chqMontant = chqMontant;
		this.chqDateEncaissement = chqDateEncaissement;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CHQ_ID", unique = true, nullable = false)
	public Integer getChqId() {
		return this.chqId;
	}

	public void setChqId(Integer chqId) {
		this.chqId = chqId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FRI_ID", nullable = false)
	public FraisInscription getFraisInscription() {
		return this.fraisInscription;
	}

	public void setFraisInscription(FraisInscription fraisInscription) {
		this.fraisInscription = fraisInscription;
	}

	@Column(name = "CHQ_Nom_Banque", nullable = false, length = 45)
	public String getChqNomBanque() {
		return this.chqNomBanque;
	}

	public void setChqNomBanque(String chqNomBanque) {
		this.chqNomBanque = chqNomBanque;
	}

	@Column(name = "CHQ_Nom_Emetteur", nullable = false, length = 45)
	public String getChqNomEmetteur() {
		return this.chqNomEmetteur;
	}

	public void setChqNomEmetteur(String chqNomEmetteur) {
		this.chqNomEmetteur = chqNomEmetteur;
	}

	@Column(name = "CHQ_Prenom_Emetteur", nullable = false, length = 45)
	public String getChqPrenomEmetteur() {
		return this.chqPrenomEmetteur;
	}

	public void setChqPrenomEmetteur(String chqPrenomEmetteur) {
		this.chqPrenomEmetteur = chqPrenomEmetteur;
	}

	@Column(name = "CHQ_Num_Cheque", nullable = false)
	public int getChqNumCheque() {
		return this.chqNumCheque;
	}

	public void setChqNumCheque(int chqNumCheque) {
		this.chqNumCheque = chqNumCheque;
	}

	@Column(name = "CHQ_Montant", nullable = false)
	public int getChqMontant() {
		return this.chqMontant;
	}

	public void setChqMontant(int chqMontant) {
		this.chqMontant = chqMontant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHQ_Date_Encaissement", length = 10)
	public Date getChqDateEncaissement() {
		return this.chqDateEncaissement;
	}

	public void setChqDateEncaissement(Date chqDateEncaissement) {
		this.chqDateEncaissement = chqDateEncaissement;
	}

}
