// default package
// Generated 18 nov. 2015 14:37:33 by Hibernate Tools 4.3.1.Final
//author : Alexandre Brosse

package ge_jpa.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Civilite generated by hbm2java
 */
@Entity
@Table(name = "civilite", catalog = "sql496886")
public class Civilite implements java.io.Serializable {

	private Integer civId;
	private String civLabel;
	private Set<Professeur> professeurs = new HashSet<Professeur>(0);
	private Set<Eleve> eleves = new HashSet<Eleve>(0);
	private Set<Responsable> responsables = new HashSet<Responsable>(0);

	public Civilite() {
	}

	public Civilite(String civLabel) {
		this.civLabel = civLabel;
	}

	public Civilite(String civLabel, Set<Professeur> professeurs, Set<Eleve> eleves, Set<Responsable> responsables) {
		this.civLabel = civLabel;
		this.professeurs = professeurs;
		this.eleves = eleves;
		this.responsables = responsables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CIV_ID", unique = true, nullable = false)
	public Integer getCivId() {
		return this.civId;
	}

	public void setCivId(Integer civId) {
		this.civId = civId;
	}

	@Column(name = "CIV_Label", nullable = false, length = 45)
	public String getCivLabel() {
		return this.civLabel;
	}

	public void setCivLabel(String civLabel) {
		this.civLabel = civLabel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "civilite")
	public Set<Professeur> getProfesseurs() {
		return this.professeurs;
	}

	public void setProfesseurs(Set<Professeur> professeurs) {
		this.professeurs = professeurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "civilite")
	public Set<Eleve> getEleves() {
		return this.eleves;
	}

	public void setEleves(Set<Eleve> eleves) {
		this.eleves = eleves;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "civilite")
	public Set<Responsable> getResponsables() {
		return this.responsables;
	}

	public void setResponsables(Set<Responsable> responsables) {
		this.responsables = responsables;
	}

}
