// default package
// Generated 18 nov. 2015 14:37:33 by Hibernate Tools 4.3.1.Final
//author : Alexandre Brosse

package ge_jpa.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classe generated by hbm2java
 */
@Entity
@Table(name = "classe", catalog = "sql496886")
public class Classe implements java.io.Serializable {

	private Integer clsId;
	private Ecole ecole;
	private Niveau niveau;
	private int clsNumero;
	private Set<Cours> courses = new HashSet<Cours>(0);
	private Set<Eleve> eleves = new HashSet<Eleve>(0);

	public Classe() {
		ecole = new Ecole();
		niveau=new Niveau();
		
	}

	public Classe(Ecole ecole, Niveau niveau, int clsNumero) {
		this.ecole = ecole;
		this.niveau = niveau;
		this.clsNumero = clsNumero;
	}

	public Classe(Ecole ecole, Niveau niveau, int clsNumero, Set<Cours> courses, Set<Eleve> eleves) {
		this.ecole = ecole;
		this.niveau = niveau;
		this.clsNumero = clsNumero;
		this.courses = courses;
		this.eleves = eleves;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CLS_ID", unique = true, nullable = false)
	public Integer getClsId() {
		return this.clsId;
	}

	public void setClsId(Integer clsId) {
		this.clsId = clsId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ECL_ID", nullable = false)
	public Ecole getEcole() {
		return this.ecole;
	}

	public void setEcole(Ecole ecole) {
		this.ecole = ecole;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "NIV_ID", nullable = false)
	public Niveau getNiveau() {
		return this.niveau;
	}

	public void setNiveau(Niveau niveau) {
		this.niveau = niveau;
	}

	@Column(name = "CLS_Numero", nullable = false)
	public int getClsNumero() {
		return this.clsNumero;
	}

	public void setClsNumero(int clsNumero) {
		this.clsNumero = clsNumero;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "classe")
	public Set<Cours> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Cours> courses) {
		this.courses = courses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "classe")
	public Set<Eleve> getEleves() {
		return this.eleves;
	}

	public void setEleves(Set<Eleve> eleves) {
		this.eleves = eleves;
	}

}
