// default package
// Generated 18 nov. 2015 14:37:33 by Hibernate Tools 4.3.1.Final
//author : Alexandre Brosse

package ge_jpa.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coordonnees generated by hbm2java
 */
@Entity
@Table(name = "coordonnees", catalog = "sql496886")
public class Coordonnees implements java.io.Serializable {

	private Integer crdId;
	private String crdAdresseLigne1;
	private String crdAdresseLigne2;
	private String crdCodePostal;
	private String crdVille;
	private String crdTelephone;
	private String crdFax;
	private String crdPortable;
	private String crdMail;

	public Coordonnees() {
	}

	public Coordonnees(String crdAdresseLigne1, String crdCodePostal, String crdVille) {
		this.crdAdresseLigne1 = crdAdresseLigne1;
		this.crdCodePostal = crdCodePostal;
		this.crdVille = crdVille;
	}

	public Coordonnees(String crdAdresseLigne1, String crdAdresseLigne2, String crdCodePostal, String crdVille,
			String crdTelephone, String crdFax, String crdPortable, String crdMail) {
		this.crdAdresseLigne1 = crdAdresseLigne1;
		this.crdAdresseLigne2 = crdAdresseLigne2;
		this.crdCodePostal = crdCodePostal;
		this.crdVille = crdVille;
		this.crdTelephone = crdTelephone;
		this.crdFax = crdFax;
		this.crdPortable = crdPortable;
		this.crdMail = crdMail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CRD_ID", unique = true, nullable = false)
	public Integer getCrdId() {
		return this.crdId;
	}

	public void setCrdId(Integer crdId) {
		this.crdId = crdId;
	}

	@Column(name = "CRD_Adresse_Ligne_1", nullable = false, length = 45)
	public String getCrdAdresseLigne1() {
		return this.crdAdresseLigne1;
	}

	public void setCrdAdresseLigne1(String crdAdresseLigne1) {
		this.crdAdresseLigne1 = crdAdresseLigne1;
	}

	@Column(name = "CRD_Adresse_Ligne_2", length = 45)
	public String getCrdAdresseLigne2() {
		return this.crdAdresseLigne2;
	}

	public void setCrdAdresseLigne2(String crdAdresseLigne2) {
		this.crdAdresseLigne2 = crdAdresseLigne2;
	}

	@Column(name = "CRD_Code_Postal", nullable = false, length = 45)
	public String getCrdCodePostal() {
		return this.crdCodePostal;
	}

	public void setCrdCodePostal(String crdCodePostal) {
		this.crdCodePostal = crdCodePostal;
	}

	@Column(name = "CRD_Ville", nullable = false, length = 45)
	public String getCrdVille() {
		return this.crdVille;
	}

	public void setCrdVille(String crdVille) {
		this.crdVille = crdVille;
	}

	@Column(name = "CRD_Telephone", length = 45)
	public String getCrdTelephone() {
		return this.crdTelephone;
	}

	public void setCrdTelephone(String crdTelephone) {
		this.crdTelephone = crdTelephone;
	}

	@Column(name = "CRD_Fax", length = 45)
	public String getCrdFax() {
		return this.crdFax;
	}

	public void setCrdFax(String crdFax) {
		this.crdFax = crdFax;
	}

	@Column(name = "CRD_Portable", length = 45)
	public String getCrdPortable() {
		return this.crdPortable;
	}

	public void setCrdPortable(String crdPortable) {
		this.crdPortable = crdPortable;
	}

	@Column(name = "CRD_Mail", length = 45)
	public String getCrdMail() {
		return this.crdMail;
	}

	public void setCrdMail(String crdMail) {
		this.crdMail = crdMail;
	}

}
