// default package
// Generated 18 nov. 2015 14:37:33 by Hibernate Tools 4.3.1.Final
//author : Alexandre Brosse

package ge_jpa.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cours generated by hbm2java
 */
@Entity
@Table(name = "cours", catalog = "sql496886")
public class Cours implements java.io.Serializable {

	private Integer crsId;
	private Classe classe;
	private CrenauHoraire crenauHoraire;
	private Professeur professeur;
	private Salle salle;
	private String nom;
	
	public Cours() {
	}

	public Cours(Classe classe, CrenauHoraire crenauHoraire, Professeur professeur, Salle salle, String nom) {
		this.classe = classe;
		this.crenauHoraire = crenauHoraire;
		this.professeur = professeur;
		this.salle = salle;
		this.nom = nom;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CRS_ID", unique = true, nullable = false)
	public Integer getCrsId() {
		return this.crsId;
	}

	public void setCrsId(Integer crsId) {
		this.crsId = crsId;
	}
	
	@Column(name = "CRS_Nom", nullable = true, length = 45)
	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLS_ID", nullable = false)
	public Classe getClasse() {
		return this.classe;
	}

	public void setClasse(Classe classe) {
		this.classe = classe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRH_ID", nullable = false)
	public CrenauHoraire getCrenauHoraire() {
		return this.crenauHoraire;
	}

	public void setCrenauHoraire(CrenauHoraire crenauHoraire) {
		this.crenauHoraire = crenauHoraire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRF_ID", nullable = false)
	public Professeur getProfesseur() {
		return this.professeur;
	}

	public void setProfesseur(Professeur professeur) {
		this.professeur = professeur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SAL_ID", nullable = false)
	public Salle getSalle() {
		return this.salle;
	}

	public void setSalle(Salle salle) {
		this.salle = salle;
	}

}
