// default package
// Generated 18 nov. 2015 14:37:33 by Hibernate Tools 4.3.1.Final
//author : Alexandre Brosse

package ge_jpa.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cycle generated by hbm2java
 */
@Entity
@Table(name = "cycle", catalog = "sql496886")
public class Cycle implements java.io.Serializable {

	private Integer cclId;
	private String cclCycleLabel;
	private Set<Niveau> niveaus = new HashSet<Niveau>(0);

	public Cycle() {
	}

	public Cycle(String cclCycleLabel) {
		this.cclCycleLabel = cclCycleLabel;
	}

	public Cycle(String cclCycleLabel, Set<Niveau> niveaus) {
		this.cclCycleLabel = cclCycleLabel;
		this.niveaus = niveaus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CCL_ID", unique = true, nullable = false)
	public Integer getCclId() {
		return this.cclId;
	}

	public void setCclId(Integer cclId) {
		this.cclId = cclId;
	}

	@Column(name = "CCL_Cycle_Label", nullable = false, length = 45)
	public String getCclCycleLabel() {
		return this.cclCycleLabel;
	}

	public void setCclCycleLabel(String cclCycleLabel) {
		this.cclCycleLabel = cclCycleLabel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cycle")
	public Set<Niveau> getNiveaus() {
		return this.niveaus;
	}

	public void setNiveaus(Set<Niveau> niveaus) {
		this.niveaus = niveaus;
	}

}
