// default package
// Generated 18 nov. 2015 14:37:33 by Hibernate Tools 4.3.1.Final
//author : Alexandre Brosse

package ge_jpa.entities;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ecole generated by hbm2java
 */
@Entity
@Table(name = "ecole", catalog = "sql496886")
public class Ecole implements java.io.Serializable {

	private Integer eclId;
	private Coordonnees coordonnees;
	private TypeEcole typeEcole;
	private String eclNom;
	private Float eclSurface;
	private Integer eclNombreSalle;
	private String eclNomResponsable;
	private Set<Classe> classes = new HashSet<Classe>(0);
	private Set<Salle> salles = new HashSet<Salle>(0);

	public Ecole() {
		this.coordonnees = new Coordonnees();
		this.typeEcole = new TypeEcole();
	}

	public Ecole(Coordonnees coordonnees, TypeEcole typeEcole, String eclNom) {
		this.coordonnees = coordonnees;
		this.typeEcole = typeEcole;
		this.eclNom = eclNom;
	}

	public Ecole(Coordonnees coordonnees, TypeEcole typeEcole, String eclNom, Float eclSurface, Integer eclNombreSalle,
			String eclNomResponsable, Set<Classe> classes, Set<Salle> salles) {
		this.coordonnees = coordonnees;
		this.typeEcole = typeEcole;
		this.eclNom = eclNom;
		this.eclSurface = eclSurface;
		this.eclNombreSalle = eclNombreSalle;
		this.eclNomResponsable = eclNomResponsable;
		this.classes = classes;
		this.salles = salles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ECL_ID", unique = true, nullable = false)
	public Integer getEclId() {
		return this.eclId;
	}

	public void setEclId(Integer eclId) {
		this.eclId = eclId;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade={CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE})
	@JoinColumn(name = "CRD_ID", nullable = false)
	public Coordonnees getCoordonnees() {
		return this.coordonnees;
	}

	public void setCoordonnees(Coordonnees coordonnees) {
		this.coordonnees = coordonnees;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TEC_ID", nullable = false)
	public TypeEcole getTypeEcole() {
		return this.typeEcole;
	}

	public void setTypeEcole(TypeEcole typeEcole) {
		this.typeEcole = typeEcole;
	}

	@Column(name = "ECL_Nom", nullable = false, length = 45)
	public String getEclNom() {
		return this.eclNom;
	}

	public void setEclNom(String eclNom) {
		this.eclNom = eclNom;
	}

	@Column(name = "ECL_Surface", precision = 12, scale = 0)
	public Float getEclSurface() {
		return this.eclSurface;
	}

	public void setEclSurface(Float eclSurface) {
		this.eclSurface = eclSurface;
	}

	@Column(name = "ECL_Nombre_Salle")
	public Integer getEclNombreSalle() {
		return this.eclNombreSalle;
	}

	public void setEclNombreSalle(Integer eclNombreSalle) {
		this.eclNombreSalle = eclNombreSalle;
	}

	@Column(name = "ECL_Nom_Responsable", length = 45)
	public String getEclNomResponsable() {
		return this.eclNomResponsable;
	}

	public void setEclNomResponsable(String eclNomResponsable) {
		this.eclNomResponsable = eclNomResponsable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<Classe> getClasses() {
		return this.classes;
	}

	public void setClasses(Set<Classe> classes) {
		this.classes = classes;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<Salle> getSalles() {
		return salles;
	}

	public void setSalles(Set<Salle> salles) {
		this.salles = salles;
	}
	
	

}
