// default package
// Generated 18 nov. 2015 14:37:33 by Hibernate Tools 4.3.1.Final
//author : Alexandre Brosse

package ge_jpa.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FraisInscription generated by hbm2java
 */
@Entity
@Table(name = "frais_inscription", catalog = "sql496886")
public class FraisInscription implements java.io.Serializable {

	private Integer friId;
	private Eleve eleve;
	private ModeDePaiement modeDePaiement;
	private float friTotal;
	private Float friMontantPaye;
	private Integer friNombreDePaiement;
	private String friAnnee;
	private Set<Cheque> cheques = new HashSet<Cheque>(0);

	public FraisInscription() {
	}

	public FraisInscription(Eleve eleve, ModeDePaiement modeDePaiement, float friTotal, String friAnnee) {
		this.eleve = eleve;
		this.modeDePaiement = modeDePaiement;
		this.friTotal = friTotal;
		this.friAnnee = friAnnee;
	}

	public FraisInscription(Eleve eleve, ModeDePaiement modeDePaiement, float friTotal, Float friMontantPaye,
			Integer friNombreDePaiement, String friAnnee, Set<Cheque> cheques) {
		this.eleve = eleve;
		this.modeDePaiement = modeDePaiement;
		this.friTotal = friTotal;
		this.friMontantPaye = friMontantPaye;
		this.friNombreDePaiement = friNombreDePaiement;
		this.friAnnee = friAnnee;
		this.cheques = cheques;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FRI_ID", unique = true, nullable = false)
	public Integer getFriId() {
		return this.friId;
	}

	public void setFriId(Integer friId) {
		this.friId = friId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ELV_ID", nullable = false)
	public Eleve getEleve() {
		return this.eleve;
	}

	public void setEleve(Eleve eleve) {
		this.eleve = eleve;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MDP_ID", nullable = false)
	public ModeDePaiement getModeDePaiement() {
		return this.modeDePaiement;
	}

	public void setModeDePaiement(ModeDePaiement modeDePaiement) {
		this.modeDePaiement = modeDePaiement;
	}

	@Column(name = "FRI_Total", nullable = false, precision = 12, scale = 0)
	public float getFriTotal() {
		return this.friTotal;
	}

	public void setFriTotal(float friTotal) {
		this.friTotal = friTotal;
	}

	@Column(name = "FRI_Montant_Paye", precision = 12, scale = 0)
	public Float getFriMontantPaye() {
		return this.friMontantPaye;
	}

	public void setFriMontantPaye(Float friMontantPaye) {
		this.friMontantPaye = friMontantPaye;
	}

	@Column(name = "FRI_Nombre_De_Paiement")
	public Integer getFriNombreDePaiement() {
		return this.friNombreDePaiement;
	}

	public void setFriNombreDePaiement(Integer friNombreDePaiement) {
		this.friNombreDePaiement = friNombreDePaiement;
	}

	@Column(name = "FRI_Annee", nullable = false, length = 45)
	public String getFriAnnee() {
		return this.friAnnee;
	}

	public void setFriAnnee(String friAnnee) {
		this.friAnnee = friAnnee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fraisInscription")
	public Set<Cheque> getCheques() {
		return this.cheques;
	}

	public void setCheques(Set<Cheque> cheques) {
		this.cheques = cheques;
	}

}
