// default package
// Generated 18 nov. 2015 14:37:33 by Hibernate Tools 4.3.1.Final
//author : Alexandre Brosse

package ge_jpa.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModeDePaiement generated by hbm2java
 */
@Entity
@Table(name = "mode_de_paiement", catalog = "sql496886")
public class ModeDePaiement implements java.io.Serializable {

	private Integer mdpId;
	private String mdpLabel;
	private Set<FraisInscription> fraisInscriptions = new HashSet<FraisInscription>(0);

	public ModeDePaiement() {
	}

	public ModeDePaiement(String mdpLabel) {
		this.mdpLabel = mdpLabel;
	}

	public ModeDePaiement(String mdpLabel, Set<FraisInscription> fraisInscriptions) {
		this.mdpLabel = mdpLabel;
		this.fraisInscriptions = fraisInscriptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MDP_ID", unique = true, nullable = false)
	public Integer getMdpId() {
		return this.mdpId;
	}

	public void setMdpId(Integer mdpId) {
		this.mdpId = mdpId;
	}

	@Column(name = "MDP_LABEL", nullable = false, length = 45)
	public String getMdpLabel() {
		return this.mdpLabel;
	}

	public void setMdpLabel(String mdpLabel) {
		this.mdpLabel = mdpLabel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeDePaiement")
	public Set<FraisInscription> getFraisInscriptions() {
		return this.fraisInscriptions;
	}

	public void setFraisInscriptions(Set<FraisInscription> fraisInscriptions) {
		this.fraisInscriptions = fraisInscriptions;
	}

}
