// default package
// Generated 18 nov. 2015 14:37:33 by Hibernate Tools 4.3.1.Final
//author : Alexandre Brosse

package ge_jpa.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Professeur generated by hbm2java
 */
@Entity
@Table(name = "professeur", catalog = "sql496886")
public class Professeur implements java.io.Serializable {

	private Integer prfId;
	private Civilite civilite;
	private Coordonnees coordonnees;
	private String prfNom;
	private String prfPrenom;
	private Set<Cours> courses = new HashSet<Cours>(0);

	public Professeur() {
	}

	public Professeur(Civilite civilite, Coordonnees coordonnees) {
		this.civilite = civilite;
		this.coordonnees = coordonnees;
	}

	public Professeur(Civilite civilite, Coordonnees coordonnees, String prfNom, String prfPrenom, Set<Cours> courses) {
		this.civilite = civilite;
		this.coordonnees = coordonnees;
		this.prfNom = prfNom;
		this.prfPrenom = prfPrenom;
		this.courses = courses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRF_ID", unique = true, nullable = false)
	public Integer getPrfId() {
		return this.prfId;
	}

	public void setPrfId(Integer prfId) {
		this.prfId = prfId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CIV_ID", nullable = false)
	public Civilite getCivilite() {
		return this.civilite;
	}

	public void setCivilite(Civilite civilite) {
		this.civilite = civilite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRD_ID", nullable = false)
	public Coordonnees getCoordonnees() {
		return this.coordonnees;
	}

	public void setCoordonnees(Coordonnees coordonnees) {
		this.coordonnees = coordonnees;
	}

	@Column(name = "PRF_Nom", length = 45)
	public String getPrfNom() {
		return this.prfNom;
	}

	public void setPrfNom(String prfNom) {
		this.prfNom = prfNom;
	}

	@Column(name = "PRF_Prenom", length = 45)
	public String getPrfPrenom() {
		return this.prfPrenom;
	}

	public void setPrfPrenom(String prfPrenom) {
		this.prfPrenom = prfPrenom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "professeur")
	public Set<Cours> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Cours> courses) {
		this.courses = courses;
	}

}
