// default package
// Generated 18 nov. 2015 14:37:33 by Hibernate Tools 4.3.1.Final
//author : Alexandre Brosse

package ge_jpa.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Responsable generated by hbm2java
 */
@Entity
@Table(name = "responsable", catalog = "sql496886")
public class Responsable implements java.io.Serializable {

	private Integer rspId;
	private Civilite civilite;
	private Coordonnees coordonnees;
	private Eleve eleve;
	private SituationFamiliale situationFamiliale;
	private String rspNom;
	private String rspPrenom;
	private String rspNumSecu;

	public Responsable() {
	}

	public Responsable(Civilite civilite, Coordonnees coordonnees, Eleve eleve, SituationFamiliale situationFamiliale) {
		this.civilite = civilite;
		this.coordonnees = coordonnees;
		this.eleve = eleve;
		this.situationFamiliale = situationFamiliale;
	}

	public Responsable(Civilite civilite, Coordonnees coordonnees, Eleve eleve, SituationFamiliale situationFamiliale,
			String rspNom, String rspPrenom, String rspNumSecu) {
		this.civilite = civilite;
		this.coordonnees = coordonnees;
		this.eleve = eleve;
		this.situationFamiliale = situationFamiliale;
		this.rspNom = rspNom;
		this.rspPrenom = rspPrenom;
		this.rspNumSecu = rspNumSecu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RSP_ID", unique = true, nullable = false)
	public Integer getRspId() {
		return this.rspId;
	}

	public void setRspId(Integer rspId) {
		this.rspId = rspId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CIV_ID", nullable = false)
	public Civilite getCivilite() {
		return this.civilite;
	}

	public void setCivilite(Civilite civilite) {
		this.civilite = civilite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRD_ID", nullable = false)
	public Coordonnees getCoordonnees() {
		return this.coordonnees;
	}

	public void setCoordonnees(Coordonnees coordonnees) {
		this.coordonnees = coordonnees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ELV_ID", nullable = false)
	public Eleve getEleve() {
		return this.eleve;
	}

	public void setEleve(Eleve eleve) {
		this.eleve = eleve;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SFA_ID", nullable = false)
	public SituationFamiliale getSituationFamiliale() {
		return this.situationFamiliale;
	}

	public void setSituationFamiliale(SituationFamiliale situationFamiliale) {
		this.situationFamiliale = situationFamiliale;
	}

	@Column(name = "RSP_Nom", length = 45)
	public String getRspNom() {
		return this.rspNom;
	}

	public void setRspNom(String rspNom) {
		this.rspNom = rspNom;
	}

	@Column(name = "RSP_Prenom", length = 45)
	public String getRspPrenom() {
		return this.rspPrenom;
	}

	public void setRspPrenom(String rspPrenom) {
		this.rspPrenom = rspPrenom;
	}

	@Column(name = "RSP_Num_Secu", length = 45)
	public String getRspNumSecu() {
		return this.rspNumSecu;
	}

	public void setRspNumSecu(String rspNumSecu) {
		this.rspNumSecu = rspNumSecu;
	}

}
