// default package
// Generated 18 nov. 2015 14:37:33 by Hibernate Tools 4.3.1.Final
//author : Alexandre Brosse

package ge_jpa.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SituationFamiliale generated by hbm2java
 */
@Entity
@Table(name = "situation_familiale", catalog = "sql496886")
public class SituationFamiliale implements java.io.Serializable {

	private Integer sfaId;
	private String sfaLabel;
	private Set<Responsable> responsables = new HashSet<Responsable>(0);

	public SituationFamiliale() {
	}

	public SituationFamiliale(String sfaLabel) {
		this.sfaLabel = sfaLabel;
	}

	public SituationFamiliale(String sfaLabel, Set<Responsable> responsables) {
		this.sfaLabel = sfaLabel;
		this.responsables = responsables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SFA_ID", unique = true, nullable = false)
	public Integer getSfaId() {
		return this.sfaId;
	}

	public void setSfaId(Integer sfaId) {
		this.sfaId = sfaId;
	}

	@Column(name = "SFA_Label", nullable = false, length = 45)
	public String getSfaLabel() {
		return this.sfaLabel;
	}

	public void setSfaLabel(String sfaLabel) {
		this.sfaLabel = sfaLabel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "situationFamiliale")
	public Set<Responsable> getResponsables() {
		return this.responsables;
	}

	public void setResponsables(Set<Responsable> responsables) {
		this.responsables = responsables;
	}

}
