// default package
// Generated 18 nov. 2015 14:37:33 by Hibernate Tools 4.3.1.Final
//author : Alexandre Brosse

package ge_jpa.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeEcole generated by hbm2java
 */
@Entity
@Table(name = "type_ecole", catalog = "sql496886")
public class TypeEcole implements java.io.Serializable {

	private Integer tecId;
	private String tecLabel;
	private Set<Ecole> ecoles = new HashSet<Ecole>(0);

	public TypeEcole() {
	}

	public TypeEcole(String tecLabel) {
		this.tecLabel = tecLabel;
	}

	public TypeEcole(String tecLabel, Set<Ecole> ecoles) {
		this.tecLabel = tecLabel;
		this.ecoles = ecoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TEC_ID", unique = true, nullable = false)
	public Integer getTecId() {
		return this.tecId;
	}

	public void setTecId(Integer tecId) {
		this.tecId = tecId;
	}

	@Column(name = "TEC_Label", nullable = false, length = 45)
	public String getTecLabel() {
		return this.tecLabel;
	}

	public void setTecLabel(String tecLabel) {
		this.tecLabel = tecLabel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeEcole")
	public Set<Ecole> getEcoles() {
		return this.ecoles;
	}

	public void setEcoles(Set<Ecole> ecoles) {
		this.ecoles = ecoles;
	}

}
